# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171014_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uid',
            field=models.CharField(default='no_uid', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='email',
            field=models.CharField(default='email', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='uid',
            field=models.CharField(default='no_uid', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
